/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.tl.ops.comp;

import java.sql.SQLException;
import java.util.ArrayList;
import org.tl.ops.comp.editors.AbstractParameterDriver;
import org.tl.ops.comp.editors.DriverComboBox;
import org.tl.ops.Common;
import org.tl.ops.comp.editors.DriverStringValue;
import org.tl.ops.dev.AbstractDevice;
import org.tl.ops.dev.KnownDevices;
import org.tl.ops.dev.debug.DebugDevice;

/**
 *
 * @author root
 */
public class SetupDialog extends javax.swing.JDialog {
    public DriverComboBox ParamDeviceType;
    public DriverStringValue ParamDeviceOrder;
    public AbstractDevice getDevice(){
        return new org.tl.ops.dev.debug.DebugDevice();
    }
    
    int[] snOrder;
    public int getVisibleSensor(int hardwareSn) throws Exception{
        if(snOrder == null){
            snOrder = new int[15];
            for(int i = 0;i<snOrder.length;i++)
                snOrder[i] = Integer.MAX_VALUE;
            String[] orderStrings = ParamDeviceOrder.getValue().split(" ");
            if(orderStrings.length > 0){
                for(int i = 0;i<orderStrings.length;i++){
                    int n = Integer.parseInt(orderStrings[i]);
                    if(n >= 0)
                        snOrder[n-1] = i;
                    else
                        snOrder[-(n+1)] = -i;
                }
            } else {
                for(int i = 0;i<orderStrings.length;i++){
                    snOrder[i] = i;
                }
            }
        }
        if(snOrder[hardwareSn] == Integer.MAX_VALUE)
            throw new Exception("Sensor configuration does not corespond to data...");
        return snOrder[hardwareSn];
    }
    
    ArrayList<AbstractParameterDriver> parameterList = new ArrayList<>();
    /**
     * Creates new form SetupDialog
     */
    public SetupDialog(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
        initComponents();
        setTitle(Common.Mls.get("Setup parameter"));
        ParamDeviceType = new DriverComboBox(cbDeviceType, "DeviceType", 
                Common.getDbConnectionCommon(), 
                KnownDevices.DefaultDevice, KnownDevices.DeviceList);
        parameterList.add(ParamDeviceType);
        ParamDeviceOrder = new DriverStringValue(tfDeviceOrder, "DeviceOrder", 
                Common.getDbConnectionCommon(), 
                KnownDevices.DefaultLineOrder);
        parameterList.add(ParamDeviceOrder);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbDeviceType = new javax.swing.JComboBox();
        btnCommit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfDeviceOrder = new javax.swing.JTextField();
        bDeviceOrderDef = new javax.swing.JButton();
        bDeviceOrderDef6L = new javax.swing.JButton();
        bDeviceOrderDef8L = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Device type");

        cbDeviceType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnCommit.setText("Commit");
        btnCommit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommitActionPerformed(evt);
            }
        });

        jLabel2.setText("Line order");

        tfDeviceOrder.setText("jTextField1");

        bDeviceOrderDef.setText("Default");
        bDeviceOrderDef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeviceOrderDefActionPerformed(evt);
            }
        });

        bDeviceOrderDef6L.setText("6L");
        bDeviceOrderDef6L.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeviceOrderDef6LActionPerformed(evt);
            }
        });

        bDeviceOrderDef8L.setText("8L");
        bDeviceOrderDef8L.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDeviceOrderDef8LActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbDeviceType, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfDeviceOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bDeviceOrderDef)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bDeviceOrderDef6L)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bDeviceOrderDef8L)
                .addContainerGap(178, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCommit))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbDeviceType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tfDeviceOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDeviceOrderDef)
                    .addComponent(bDeviceOrderDef6L)
                    .addComponent(bDeviceOrderDef8L))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 309, Short.MAX_VALUE)
                .addComponent(btnCommit))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCommitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommitActionPerformed
        try{
            for(AbstractParameterDriver param : parameterList)
                param.commit();
            Common.getDbConnectionCommon().commit();
            setVisible(false);
        }catch(Exception ex){
            Common.Log.exception("Save new parameters...", ex);
        }
    }//GEN-LAST:event_btnCommitActionPerformed

    private void bDeviceOrderDefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeviceOrderDefActionPerformed
        tfDeviceOrder.setText(KnownDevices.DefaultLineOrder);
    }//GEN-LAST:event_bDeviceOrderDefActionPerformed

    private void bDeviceOrderDef6LActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeviceOrderDef6LActionPerformed
        tfDeviceOrder.setText(KnownDevices.DefaultLineOrder6L);
    }//GEN-LAST:event_bDeviceOrderDef6LActionPerformed

    private void bDeviceOrderDef8LActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDeviceOrderDef8LActionPerformed
        tfDeviceOrder.setText(KnownDevices.DefaultLineOrder8L);
    }//GEN-LAST:event_bDeviceOrderDef8LActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bDeviceOrderDef;
    private javax.swing.JButton bDeviceOrderDef6L;
    private javax.swing.JButton bDeviceOrderDef8L;
    private javax.swing.JButton btnCommit;
    private javax.swing.JComboBox cbDeviceType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tfDeviceOrder;
    // End of variables declaration//GEN-END:variables
}
